name: Build APK
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Permission
         run: chmod +x gradlew
      - name: Compile
         run: ./gradlew assembleDebug
      - name: Artifact
        uses: actions/upload-artifact@v4
        with:
      - name: apks
        path: "**/build/outputs/apk/debug/*.apk"